import type { LucideIcon } from "lucide-react";
import {
  UtensilsCrossed,
  Landmark as LandmarkIcon,
  TreePine,
  Ticket,
  ShoppingBag,
  Heart,
  Plane,
  BedDouble,
} from "lucide-react";
import type { AttractionType, DayKey, OpeningHours } from "./attraction.types";

export const ATTRACTION_TYPES: AttractionType[] = [
  "Restaurant",
  "Bar",
  "Café",
  "Supermarket",
  "Food Truck",
  "Museum",
  "Gallery",
  "Theatre",
  "Religious",
  "Landmark",
  "Park",
  "Beach",
  "Zoo",
  "Hiking",
  "Cinema",
  "Concert",
  "Casino",
  "Amusement Park",
  "Water Park",
  "Escape Room",
  "Stand-Up Comedy",
  "Nightclub",
  "Mall",
  "Store",
  "Market",
  "Spa",
  "Gym",
  "Pool",
  "Flight",
  "Train",
  "Car Rental",
  "Cruise / Port",
  "Bus",
  "Taxi / Rideshare",
  "Hotel",
  "Apartment",
  "Hostel",
  "Villa",
];

export const TYPE_CATEGORIES: Record<string, AttractionType[]> = {
  "Food & Drink":    ["Restaurant", "Bar", "Café", "Supermarket", "Food Truck"],
  "Culture":         ["Museum", "Gallery", "Theatre", "Religious", "Landmark"],
  "Nature & Outdoor":["Park", "Beach", "Zoo", "Hiking"],
  "Entertainment":   ["Cinema", "Concert", "Casino", "Amusement Park", "Water Park", "Escape Room", "Stand-Up Comedy", "Nightclub"],
  "Shopping":        ["Mall", "Store", "Market"],
  "Wellness":        ["Spa", "Gym", "Pool"],
  "Transportation":  ["Flight", "Train", "Car Rental", "Cruise / Port", "Bus", "Taxi / Rideshare"],
  "Accommodation":   ["Hotel", "Apartment", "Hostel", "Villa"],
};

export const CATEGORY_ORDER: string[] = [
  "Food & Drink",
  "Culture",
  "Nature & Outdoor",
  "Entertainment",
  "Shopping",
  "Wellness",
  "Transportation",
  "Accommodation",
];

export const CATEGORY_COLORS: Record<string, string> = {
  "Food & Drink":    "#F59E0B",
  "Culture":         "#7C3AED",
  "Nature & Outdoor":"#059669",
  "Entertainment":   "#E11D48",
  "Shopping":        "#0891B2",
  "Wellness":        "#10B981",
  "Transportation":  "#475569",
  "Accommodation":   "#D97706",
};

export const DAY_KEYS: DayKey[] = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];

export const DEFAULT_OPENING_HOURS: OpeningHours = {
  Mon: { closed: false, open: "09:00", close: "18:00" },
  Tue: { closed: false, open: "09:00", close: "18:00" },
  Wed: { closed: false, open: "09:00", close: "18:00" },
  Thu: { closed: false, open: "09:00", close: "18:00" },
  Fri: { closed: false, open: "09:00", close: "18:00" },
  Sat: { closed: false, open: "10:00", close: "17:00" },
  Sun: { closed: true, open: "10:00", close: "17:00" },
};

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  "Food & Drink":    UtensilsCrossed,
  "Culture":         LandmarkIcon,
  "Nature & Outdoor":TreePine,
  "Entertainment":   Ticket,
  "Shopping":        ShoppingBag,
  "Wellness":        Heart,
  "Transportation":  Plane,
  "Accommodation":   BedDouble,
};

export const COUNTRIES: string[] = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Brazzaville)",
  "Congo (Kinshasa)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "São Tomé and Príncipe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
